#!/bin/sh                                                                                                                            

echo "Please enter your text";
read text

combine="$text "

file="./testFile.txt"

if [ -f "$file" ]
then
echo "$file found."
touch $combine >> $file
echo $combine >> $file
else
echo "$file not found. Will create the file and add entry now."
touch $file
$combine >> $file
fi
